# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 02:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='menu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='menu_review', to='menus.Menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
