# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20180125_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='media/default_image.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default='media/default_image.png', upload_to=''),
        ),
    ]
