# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_notice', to=settings.AUTH_USER_MODEL),
        ),
    ]
