# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_notice_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='media/default_image.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default='media/default_image.png', upload_to=''),
        ),
    ]
