# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20180126_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to=''),
        ),
    ]
